### ISSUE TITLE
Client side?

### ISSUE THREAD

**Issue by cameronroe** [webflow/js-webflow-api#10]
Any thoughts on making this work client-side as well? Would love to have a simple wrapper to use Webflow inside of the client js on a webflow site that has some Ajax-style features. For example, if I wanted to incorporate an infinite scroll widget on the site, I would need to fetch from the API on the client and don't really like the idea of setting up a proxy... 

Would even consider contributing toward something like this. Thoughts?

**Comment by cameronroe** [comment]
?

**Comment by n-johnson** [comment]
Currently, the Webflow API only supports authenticated access, which means using the API from the browser would require your secret access token (should be considered to be equivalent to your password) to be shared publically. This would give anybody the ability to update all of your CMS content.

So while updating this npm module to have browser support solves part of the problem, the bigger issue here is what the API itself actually supports. For now, the best way to accomplish what it sounds like you are trying to do is by making the requests to the webflow api from a backend server where your API keys don't have to be publically exposed. Sorry there isn't currently another option as I know you were trying to avoid that :/

**Comment by cameronroe** [comment]
Thanks @n-johnson. I'm just wondering why the API doesn't support a client credential for apps? This is common amongst other APIs. Will it be available in the future?

**Comment by cameronroe** [comment]
I think it's important to have this functionality as it improves the client-side experience. For example, if I want to implement an infinite scroll section that fetches new data from the API, ideally I should be able to do that from the client-side.

**Comment by cameronroe** [comment]
@n-johnson ?

**Comment by n-johnson** [comment]
> I'm just wondering why the API doesn't support a client credential for apps? 

Can you explain how this would work? Where are the API credentials coming from, and who has access to them?

I'm not sure if [Client Credentials](https://tools.ietf.org/html/rfc6749#section-1.3.4) would do quite what you were hoping here - if some form of it were to be used in this manner, it still would be publically exposing API keys that would allow anyone to modify your site. 

> I think it's important to have this functionality as it improves the client-side experience. For example, if I want to implement an infinite scroll section that fetches new data from the API, ideally I should be able to do that from the client-side.

I think an unauthenticated, public, read-only API may be what you are wanting? We don't currently have support for this, but I can add it to our feature wishlist?

**Comment by plomteuxquentin** [comment]
Hi @n-johnson ,

Would it not be possible to have that feature with [user login](https://wishlist.webflow.com/ideas/DESIGNER-I-11). Then we'll be able to use authentification token to request the API like [JWT](https://jwt.io/).

Is it something you have in mind?

also do you have a public roadmap for the API?

**Comment by TomS-** [comment]
@n-johnson 

I've been working on something that implements AlpineJS with Webflow in hopes to get around a lot of the limitations. Such as nested collections limiting to 5 or only having 1 per page. It's API driven and at the moment it has to ping to my server to do a PHP curl then return the result. Having the fetch an API that then fetches an API isn't the most performant.

Eliminating the middle man will be much preferred. There are plenty of platforms you expose the API key, TinyMCE, Snipcart, Shopify. Being able to access the API let's us do things like front-end forms that populate the CMS, it really steps up Webflow for developers that may otherwise turn away because of the limitations.

A lot of these work by doing trusted URL's. This prevents anyone using it outside of the URL's that are trusted, this could be set in the API key area. You could even default trusted URL's that are on the Webflow Project. 

I understand it's too long in the tooth now to just implement something like this without breaking current integrations. This is why you'll need a new area to generate and use a front-end API key like Shopify does their Storefront API key.

**Comment by jacobbroughton** [comment]
> > I'm just wondering why the API doesn't support a client credential for apps?
> 
> Can you explain how this would work? Where are the API credentials coming from, and who has access to them?
> 
> I'm not sure if [Client Credentials](https://tools.ietf.org/html/rfc6749#section-1.3.4) would do quite what you were hoping here - if some form of it were to be used in this manner, it still would be publically exposing API keys that would allow anyone to modify your site.
> 
> > I think it's important to have this functionality as it improves the client-side experience. For example, if I want to implement an infinite scroll section that fetches new data from the API, ideally I should be able to do that from the client-side.
> 
> I think an unauthenticated, public, read-only API may be what you are wanting? We don't currently have support for this, but I can add it to our feature wishlist?

A client side read-only api would be extremely nice to have
